### ISSUE TITLE
XML-DB Setup + REST + Docker

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#1]
We need a XML database for our project. 

- Inform about XML databases and choose one for our project. Consider that we want to use REST to access the database. 
- Do the setup of an XML-Database, preferably with Docker. 
- Provide an explanation on how to setup the XML-DB for other team members.

**Comment by m273d15** [comment]
I tried it locally with docker, maybe my experience can help you:
 I used the command:
```sh
sudo docker run -tdi \                    
    --name basexhttp \
    --publish 1984:1984 \
    --publish 8984:8984 \
    --volume ~/BaseXData:/srv/BaseXData \
    basex/basexhttp:8.6.4
```
I added `-d` (daemon) to the documented command and rather use version 8.6.4 instead of latest (nightly build).

Attention the permissions of ~/BaseXData on the host machine are important, since basex does not work if the permissions are to strict.
I moved our xml into the BaseXData directory and created via the cli `basex` in the container with the command `CREATE DATABASE beer /srv/BaseXData/<xmlname>` a new database. And it was possible to use the REST service with using XQuery out of the box. I tried the GET command `http://localhost:8984/rest/beer?query=/artifacts` and it worked like a charm!

**Comment by Armagetron** [comment]
I added a Dokcerfile based on basex/basexhttp which includes the content of this repository into the image.

It uses the build-in web server of basex

**Comment by m273d15** [comment]
Nice, i added a small script to simplify the build and run process for users who are not familiar with docker.
I also added the packages `libxml2-utils`, `xsltproc` and `vim` to the image.
The first packages provide the functionality to play with the XSLT and XSD. If you prefer to work on the container you can use vim. If you don't like it, feel free to remove it

**Comment by m273d15** [comment]
Creating a following story to integrate the XML data into the basex database
