### ISSUE TITLE
XSLT - Transform LIDO to our own XML 

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#2]
We want to tranform the XML-Format in our data from LIDO to something that we can use more easily.

- Write a XSLT for the transformation from LIDO to a handier format
- Write a XSD to verify our format

**Comment by m273d15** [comment]
As you see in commit ef4de848d262ac6bb8a6a4d1ee05d24b81df9d6a, i created a small xsl creating a xml as below. I removed some information so if you need some informations from the original document inform me or adjust the xsl AND xsd by youself. Since our main idea is to create a timeline i also transformed all date information as earliestDate and latestDate to provide all informations.
 
If you like to test the xsl and xsd, simply run the `test.sh` (you need the cli tools `xmllint` (ubuntu package: `libxml2-utils`) and `xsltproc` (ubuntu package: `xsltproc`)).
```xml
<artifacts xmlns:lido="http://www.lido-schema.org">
  <artifact>
    <type>Gemälde</type>
    <title>Gaststätte Zum alten Landhaus am Eppendorfer Marktplatz</title>
    <location>
      <name>Museum für Hamburgische Geschichte, Hamburg</name>
      <inventoryNr>1971,2</inventoryNr>
    </location>
    <description>Gemälde der Gaststätte "Zum alten Landhaus Johann Rieper". Abgebildet ist ein einstöckiges Fachwerkhaus im Hintergrund mit einem Restaurant-Vorbau und einem Biergarten im Vordergrund. Am Giebel des Restaurants Werbung für Bavaria-Bräu.</description>
    <actors>
      <actor>
        <namae>unbekannt</namae>
        <role>Maler/in</role>
      </actor>
    </actors>
    <dates>
      <displayDate>um 1914</displayDate>
      <earliestDate>1904</earliestDate>
      <latestDate>1924</latestDate>
    </dates>
    <urls>
      <url>M:\bilder_museumplus\MHG\Gemälde&amp;Malerei\Gemädescan/1971,2 - 1989,845.jpg</url>
      <url>M:\bilder_museumplus\MHG\Gemälde&amp;Malerei\Malerei\1971/1971-2_002.jpg</url>
      <url>M:\bilder_museumplus\MHG\Gemälde&amp;Malerei\Malerei\1971/1971-2_001.jpg</url>
    </urls>
  </artifact>
   ...
</artifacts>
```

**Comment by m273d15** [comment]
Please reopen if we have to adjust the schema or stylesheet!
