### ISSUE TITLE
Detail View with Microformats

### ISSUE THREAD

**Issue by mhalilovic** [awildturtok/hamburg-beer-xml#5]
We need a detail view for our entries in the timeline.

- Build a detail view for our Frontend using Microformats and RDF's.

**Comment by TortugaAttack** [comment]
instead of microformats RDFa will be used in addtion with the Dublin Core.

**Comment by TortugaAttack** [comment]
- Wrote own lightweight SPARQL API in pure js and integrated it.  [SimpleSPARQLJS](https://github.com/TortugaAttack/simplesparqljs)
- Problem with EUROPEANA SPARQL endpoint: The triplestore does not contain the information that they claim it has. Thus i will write an email asking if they can add the data (again). 
- Further on the dataset makes use of discouraged triples. F.e. they use 
`exa:Picture1ID dc:creater "Prename Surname" `
instead of linking to the creator resource f.e.: 
```
exa:Picture1ID dc:creator exa:Prename_Surname
exa:Prename_Surname rdfs:label "Prename Surname"
```
I will also write this in the email.  (This is not a direct problem for us, but not good either as it can result into higher missmatches in the RDFa resources.)

**UPDATE**
email is done.

**Comment by TortugaAttack** [comment]
Europeana has triples (no clue why they were not shown to me before)
i randomly checked if there is any kind of information for our dataset in it and it seems there is none. 

Further on the dataset has some problems. 
Sometimes the Place is in the title, sometimes the title differs from the real title (in description) 
Persons are randomly `Prename Surname` or `Surname, Prename`
dates are not wellformated: f.e. displayDate is `um 1904` or else

**Comment by TortugaAttack** [comment]
Further on the location is often provided in "actual place, city"

**Comment by mhalilovic** [comment]
Nice!
![capture2](https://user-images.githubusercontent.com/2799766/28173364-872a7b84-67ee-11e7-80d3-4f01ec2870f3.PNG)
